### DISCUSSION TITLE
General Setup/Config outline

### DISCUSSION THREAD

**Discussion by Extrapilot1** [brunosabot/streamline-card#19] [Q&A] [answered]
Hi all- and to Bruno- thanks so much for this work.

I have a tech (implementation) question.

I have no idea if this particular project requires the system to be in storage mode, hybrid, YAML etc. And I think it is fair to say that the lack of **current** documentation in HA is a real problem. People with significant experience in coding JS or Jninja etc post about spending 8 hours debugging what amounts to a '-' that was deprecated, or which is needed in JS and not JNinja or whatever. 

I was very happy to see in this project code/examples for both sides of the equation- so thank you for that to all involved. 

So yea-  the question is how to deal with UI/YAML installs specifically. Where do the includes go? It may have been that they went into the raw dashboard code for UI mode 3 months ago (per some docs I found on the precursor module to streamline), but now, you may well get an error about a reference to a module as a Resource entry vs a manual entry etc. 

Best,
Rob

**Comment by brunosabot** [comment, marked as answer]
Hello there!

Short story: whatever!
The only think that will be different could be the complexity of implementation.

_Disclamer: there might exists other way to do this, but if there is, I have no idea about how to work with._

# Using the YAML mode

_I'll give you my way of doing things, but you might need to change the paths_

I have a `lovelace` folder which contains a `streamline-card` folder. Inside of it, I have as many file I have templates. So basically:
```
lovelace/
    streamline-card/
        bubble_alarm.yaml
        bubble_aqi.yaml
        ...
```
To be able to use templates, I just need to include in my yaml files: `streamline_templates: !include_dir_named ../streamline_templates/` then the views. Remember that based on the place where are your lovelace dashboard, the path could change.

At this point, you'll have access to the whole templates in your configuration file

```yaml
title: 'My Dashboard'
views:
  - # Your views in yaml mode
streamline_templates: !include_dir_named ../streamline_templates/
```

# Using the UI

It's a bit more tricky. You'll have to use the raw config editor for your view. If you have several views in your Home Assistant instance, you'll have to repeat the how-to.

In the raw config editor, you will need to add the `streamline_templates:` with a child for each card and then the template. So basically:
```yaml
streamline_templates:
  bubble_state:
    default:
      - name: Test
    card:
      type: custom:bubble-card
      card_type: button
      button_type: state
      entity: '[[entity]]'
      name: '[[name]]'
      show_state: true
  default_entity:
    card:
      type: entities
      entities:
        - entity: '[[entity]]'
views:
    # Here will go the code generated from the UI edition
```
