### DISCUSSION TITLE
Support Object/Array Variables in UI for Nested Streamline Cards

### DISCUSSION THREAD

**Discussion by loocd** [brunosabot/streamline-card#28] [Ideas]
First of all - amazing card, thank you very much for your efforts!

So far I have used decluttering-cards and with that I have set up a bunch of nested templates, which is not possible by using the UI.

For example, I have UI item for users to select a scene (technically calling a script), which is present on every page, with different scenes per page.
![image](https://github.com/user-attachments/assets/702aa8c0-2fbc-477c-8ed2-a40093bf41b7)
![image](https://github.com/user-attachments/assets/e7f11001-67a3-4dd4-9394-d1d6e6c627c3)

The entire card is set up and styled using a decluttering card (padding, rounded corners, size, scrolling behavior etc.)  and then on each page, the scenes to be shown are set as variables.
But each item within that card is also a template, which again sets icon sizes, colors, padding, etc.

That way I can have a standardized container and then select a different number of standardized items/scenes (depending on the current page) and am not locked into a fixed amount of scenes.

So basic setup (styles removed):
```
general_scene-card:
    card:
      type: custom:stack-in-card
      mode: horizontal
      card_mod:
        style: //removed
      cards: '[[Scenes]]'
  general_scene-card-item:
    default:
      - Color: rgb(var(--primary-color-rgb))
      - Data: null
    card:
      type: custom:mushroom-entity-card
      card_mod:
        style: //removed
      entity: '[[Script]]'
      name: '[[Name]]'
      secondary_info: none
      icon_color: '[[Color]]'
      layout: vertical
      tap_action:
        action: perform-action
        perform_action: '[[Script]]'
        data: '[[Data]]'
        target: {}
      hold_action:
        action: none
      double_tap_action:
        action: none
```

and then this is how I use it:
```
type: custom:decluttering-card
template: general_scene-card
variables:
  - Scenes:
      - type: custom:decluttering-card
        template: general_scene-card-item
        variables:
          - Name: Film
          - Script: script.scene_film
      - type: custom:decluttering-card
        template: general_scene-card-item
        variables:
          - Name: Lesen
          - Script: script.scene_lesen
      - type: custom:decluttering-card
        template: general_scene-card-item
        variables:
          - Color: red
          - Name: Alles aus
          - Script: script.scene_all_off_area
          - Data:
              Area: Wohnzimmer
```

This is not possible via the UI of the streamline-card as it does not allow object or array variables.
