### DISCUSSION TITLE
adding streamline_templates: !include_dir_named ../streamline_templates/

### DISCUSSION THREAD

**Discussion by AlexKusnezov** [brunosabot/streamline-card#46] [General]
Guys, I'm not sure how to add this, readme says:
```
Include Templates in Dashboard: In your dashboard configuration file, add:
streamline_templates: !include_dir_named ../streamline_templates/
```
What do you mean by "dashboard configuration file"? configuration.yaml?
It is not `Raw configuration editor`, because adding this I'll get:
```
Unable to parse YAML: YAMLException: unknown tag !<!include_dir_named> (14:66) 11|... off 121 ... 13l ... 14l ... named ../streamline_templates/ —
-^ 15|... 16 | ...
```
![Screenshot 2025-02-10 at 14 21 38](https://github.com/user-attachments/assets/79d37695-d006-471f-ae3a-75e01f5ecf4a)

**Comment by brunosabot** [comment]
Hello @AlexKusnezov,

This only applies if you are using the YAML mode of the configuration, and it looks like you are using the UI.
Unfortunately, you can't split the configuration if you are using the UI mode, you need to put all the template in there, meaning:
```yaml
streamline_templates:
  my_streamline_template:
    # your config here
  my_other_streamline_template:
    # your config here
  # etc.
views:
  - type: sections
    max_columns: 4
    title: Your dashboard name
    path: your-dashboard-path
    icon: mdi:your-icon
    sections:
      # Your UI here
```
