### DISCUSSION TITLE
Template inheritance like button-card

### DISCUSSION THREAD

**Discussion by shakin89** [brunosabot/streamline-card#53] [Q&A]
Hi, i'm pretty new to bubble-card and streamline-card. 
I'm on the way to convert my yaml dashboard from button-card to bubble+streamline. 
In button-card templates i can inherhits from other template. 
E.g. i have two or three types of light card, all with the same base.  here is an extract 
```yaml
base_card:
  styles:
    card:
      - padding: 0px
      - margin: 0px
      - border-radius: 10px
      - font-size: 14px
switch_card:
  template:
    - base_card
  action: toggle
  variables:
    label: "Default Label"
  color_type: icon
  icon: mdi:power-socket-it
  label: "[[[ return variables.label ]]]"
icon_card:
  template:
    - base_card
  variables:
    entity: ""
  color_type: icon
  color: var(--state-icon-color)

```

is there a similar way to do this in streamline?
Or which would be the best way to do a similar thing in streamline+bubble?
