### DISCUSSION TITLE
Set Cards Option as a variable

### DISCUSSION THREAD

**Discussion by AlexKusnezov** [brunosabot/streamline-card#59] [Q&A]
Hey guys, is there a way to enable/disable entire card options with variables, e.g.:

I have this consumption card template, where I try to add the option `update_interval:` and by deafult it should be nothing. But for some I would just use something like `update_interval: 30` to appear as an card option when I use this template.
I've tried it like this so far

```
  consumption_card:
    default:
      - verbrauch_name: Verbrauch
```
 `     - update_interval: ''`
```
    card:
      type: custom:mini-graph-card
      entities:
        - '[[verbrauch_raum]]'
      name: '[[verbrauch_name]]'
      align_header: center
      align_icon: left
      align_state: center
      line_color: red
      animate: true
      hour24: true
      height: 220
      decimals: 0
```
`      '[[update_interval]]'`
```
      color_thresholds:
        - value: 0
          color: '#44ce1b'
        - value: 10
          color: '#44ce1b'
        - value: 200
          color: '#bbdb44'
        - value: 400
          color: '#f7e379'
        - value: 500
          color: '#f2a134'
        - value: 1000
          color: '#e51f1f'
        - value: 2000
          color: '#ff0000'
        - value: 3000
      show:
        icon: false
        name: true
        state: true
        fill: true
        extrema: false
        graph: bar
```

However having it like this gives me the follwing error:
`Unable to parse YAML: YAMLException: can not read an implicit mapping pair; a colon is missed (297:28) 294 | hour24: true 295 | height: 220 296 | decimals: 0 297 | '[[update_interval]]' ----------------------------------^ 298 | color_thresholds: 299 | - value: 0`
Do you know a workaroung for this?
