### DISCUSSION TITLE
use as replacement for config-template-card

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [brunosabot/streamline-card#66] [Q&A]
Hi, thx for creating this, I am experimenting its use in my config.
For that, I would need to make a card config dynamic, based n the state of an Frontend element, namely an input_select.

That input_select sets the precision of the Sankey chart card and in config-template-card that looks like:

```
type: custom:config-template-card
entities:
  - input_select.sankey_min_state
variables:
  min_state: states['input_select.sankey_min_state'].state
card:
  type: custom:sankey-chart
  title: Energie verbruik
  min_state: ${min_state}
```
so, depending on the select state, the cards is redrawn, and only then (well, of course it also redraws on state changes of the entities in the chart, but that goes without saying..)

this is all in 1 file, no need for templates.

I cant get my head around the options that streamline-card offers for this, so please could you help me out? can this be done easily, do I need a 'templates' for that, or should I stay with config-template-card....

second topic: 
Is streamline-card transparent regarding the card_mod modifications we set to the child card? 
Asking because my first experiments lost the modifications I set to the card, modifications that do work if the card is on its own

thanks for any hint

**Comment by Mariusthvdb** [comment]
answering myself here:
yes the card is transparent

using this panel view config
```
title: Energie Sankey
path: energie_sankey
icon: mdi:chart-sankey-variant
panel: true
cards:
  - type: custom:streamline-card
    template: sankey_energie_grafieken
    variables:
      min_state: input_select.sankey_min_state
```

and a template with:

```
card:
  type: vertical-stack
  cards:
    - type: tile
      entity: input_select.sankey_min_state
      features:
        - type: select-options
      features_position: inline
    - type: custom:sankey-chart
      title: Energie verbruik
      <<: &sankey_config
        card_mod:
          style:
            sankey-chart-base:
              $:
                ha-card:
                  $: |
                    h1.card-header {
                      background: var(--background-color-off) !important;
                      font-weight: 400 !important;
                      font-size: 20px !important;
                      color: var(--text-color-off) !important;
                      padding: 0px 12px !important;
                      margin: 0px 0px 16px 0px !important;
                    }
        show_names: true
        height: 500
        round: 2
        unit_prefix: k
        min_state_javascript: >
          return states['[[min_state]]'].state;
        layout: horizontal
      sections:
etcetcetc
```

The csrd-headers are nicely modded. which is great, and an advantage over config-template-card that breaks this somehow.
