### DISCUSSION TITLE
Some way to "nest" variables to allow streamlining across multiple dashboards.

### DISCUSSION THREAD

**Discussion by tismondo** [brunosabot/streamline-card#71] [Ideas]
I don't know if I can articulate what I'm talking about effectively -- it's possible there's already a solution for this and I just haven't discovered it yet.

- Imagine I want to make changes to the look of a card as well as one of the entity_ids it references. This card template is used identically across lots of different dashboards (for example, each family member has a card representing the Kitchen lights on all of their dashboards) 
- First, I'd need to edit the template.  That's easy with streamline card! One edit fixes the card design across all the cards in every dashboard.
- But in order to edit the entity_id as mentioned above, I'd need to go and edit every single dashboard one at a time. When making really big changes to the frontend, all those tiny changes can really add up,  But since this is the _streamline card_ maybe there can be a solution?!

-  What if there were a way to have something like **variable templates**?  

So instead of the below card yaml (where you have to edit each and every one for every dashboard)

```
type: custom:streamline-card
template: test
variables:
  - var1: sensor.one
  - var2: sensor.two
  - var3: sensor.three
```

You could have a linked reference to a list of variables:

```
type: custom:streamline-card
template: test
variable_template: var_template_1
```

And so of course in the streamline templates folder you'd need something like a variable_templates.yaml file that would include, for example

```
var_template_1:
  - var1: sensor.one
  - var2: sensor.two
  - var3: sensor.three
```

Does this make sense?  Am I over thinking this and there's already an easy, better way to do this?
