### DISCUSSION TITLE
[Feature Request] Inherit variables or a set of variables based on a given value

### DISCUSSION THREAD

**Discussion by anthonyma94** [brunosabot/streamline-card#9] [Ideas]
Currently, all variables have to be passed in the way it is, with no way of deriving variables based on another. It would be nice if I could set and parse variables based on another.

Example
```yaml
streamline_templates:
  hallway:
    default:
      - options:
          small:
            card_layout: normal
            show_state: false
        large:
            card_layout: large-2-rows
            show_state: true
        screen_size: small

        # alternatively use templating?
        card_layout: ${{ "normal" if vars['screen_size'] == "small" else "large-2-rows" }}
    card:
      type: custom:bubble-card
      card_type: button
      button_type: state
      icon: mdi:door-sliding
      name: Upstairs Hallway
      tap_action:
        action: toggle
      sub_button:
        - show_background: false
          show_state: "[[options.[screen_size].show_state]]"
          entity: binary_sensor.upstairs_sensors
      card_layout: "[[options.[screen_size].card_layout]]" # or just [[card_layout]] if using alternative option
      show_icon: true
      entity: light.upstairs_hallway

# To use
type: custom:streamline-card
template: hallway
variables:
  - screen_size: large
```
