### ISSUE TITLE
JavaScript templates cannot handle non-primitive variables

### ISSUE THREAD

**Issue by anthonyma94** [brunosabot/streamline-card#10]
**Describe the bug**  
When using JavaScript templates, referencing non-primitive variables (objects & arrays) will result in errors. The error depends on the parser, but nothing will act as expected.

**To Reproduce**
With these variables:
```yaml
default:
  - card:
      type: custom:mushroom-title-card
      title: hello
  - cards:
    - type: custom:mushroom-title-card
      title: hello
```

This works:
```yaml
card:
  type: vertical-stack
  cards:
    - "[[card]]"
  # or
  cards: "[[cards]]"
```

But this doesn't:
```yaml
card:
  type: vertical-stack
  cards_javascript: "['[[card]]']"
  # or
  cards_javascript: "'[[cards]]'"
```

**Expected behavior** 
I expect both options to work.

**Comment by brunosabot** [comment]
Hello @anthonyma94,

It's hopefully fixed in version 0.0.7 released this morning.
Could you tell me if it's OK for you?

**Comment by anthonyma94** [comment]
Thanks for the quick response! I'm getting a different error for objects: Uncaught (in promise) SyntaxError: unexpected token: ':'. Arrays seem to be fine with my limited testing.

```yaml
default:
  - testing:
      text: hello
card:
  type: custom:mushroom-title-card
  title_javascript: "'[[testing]]'.text"
```

**Comment by brunosabot** [comment]
That's normal, this is not valid javascript: it transposes to: `{"text":"hello"}.text` which is invalid in JavaScript. You can test in the console.
If you have such need, you probably need this template:
```yaml
default:
  - testing:
      text: hello
card:
  type: custom:mushroom-title-card
  title_javascript: "('[[testing]]').text"
```

Basically, the parenthesis will instantiate the object for real and then you are able to get its properties.
