### ISSUE TITLE
e.default is not iterable

### ISSUE THREAD

**Issue by andreasbrett** [brunosabot/streamline-card#11]
**Describe the bug**  
With the latest 0.0.7 release I get errors for some (but not all) streamline card instances.

**Screenshots** 
![image](https://github.com/user-attachments/assets/e66fe71d-e081-4afd-95b0-b53a031b893d)

**YAML**  
Here's the corresponding template and it's instantiation.

```yaml
gap:
  default:
    height: 12px
  card:
    type: markdown
    content: ' '
    card_mod:
      style: |
        ha-card {
          max-height: [[height]];
          background: none;
        }
```

```yaml
type: custom:streamline-card
template: gap
```

Here's a template and instantiation that still works with 0.0.7.

```yaml
cast_internet_radio_button:
  card:
    type: custom:button-card
    name: '[[label]]'
    color_type: card
    tap_action:
      action: call-service
      service: script.radio_starten
      data:
        player: >-
          [[[ return "media_player." + states["input_text.media_player"].state
          ]]]
        sender: '[[name]]'
    styles:
      card:
        - height: 2.5rem
        - background: var(--paper-item-icon-active-color)
        - color: var(--paper-item-icon-inactive-color)
        - font-size: 1rem
```

```yaml
type: custom:streamline-card
template: cast_internet_radio_button
variables:
  - label: 🌠 Alternative
  - name: Star FM - Alternative Rock
```

**Comment by andreasbrett** [comment]
Another template that does not work is this:

```yaml
room_button:
  default:
    scene_helper: ''
    badge_icon: ''
    badge_entity_name: ''
    badge_entity_state: ''
    badge_color: blue
  card:
    type: custom:mushroom-template-card
    entity: '[[entity]]'
    tap_action:
      action: navigate
      navigation_path: '[[hashtag]]'
    hold_action:
      action: toggle
    icon: mdi:[[icon]]
    icon_color: |-
      {% if is_state('[[entity]]', 'on') %}
      orange
      {% endif %}
    primary: '[[name]]'
    secondary: '{{ states(''[[scene_helper]]'') if ''[[scene_helper]]'' != '''' }}'
    multiline_secondary: true
    badge_icon: >-
      {{ 'mdi:[[badge_icon]]' if is_state('[[badge_entity_name]]',
      '[[badge_entity_state]]') }}
    badge_color: '[[badge_color]]'
```

```yaml
type: custom:streamline-card
template: room_button
variables:
  - entity: light.alle_lichter_wohnzimmer
  - name: Wohnzimmer
  - hashtag: '#wohnzimmer'
  - scene_helper: sensor.aktuelle_szene_wohnzimmer_name
  - icon: sofa
  - badge_icon: music
  - badge_entity_name: binary_sensor.medien_aktiv_wohnzimmer
  - badge_entity_state: 'on'
```
