### ISSUE TITLE
Error with type image

### ISSUE THREAD

**Issue by Pulpyyyy** [brunosabot/streamline-card#12]
Hello,

Switching from decluttering-card to this new one, i have a problem with card image:

![image](https://github.com/user-attachments/assets/84d83ab1-e161-4a69-b27d-d2b3cb772668)

Here is a template:
```
type: custom:layout-card
layout_type: grid
cards:
  - type: picture-elements
    image: /local/images/empty.png
    elements:
      - type: custom:streamline-card
        template: floor_image_generic
        variables:
          - entity: person.admin
          - img: /local/images/red.png
          - state: unknown

```
```
streamline_templates:
  floor_image_generic:
    default:
      - state: 'on'
    element:
      type: image
      entity: '[[entity]]'
      image: /local/images/empty.png
      style:
        top: 50%
        left: 50%
        width: 100%
      state_image:
        '[[state]]': '[[img]]'
      tap_action:
        action: none
```
And chrome error message:
```
create-element-base.ts:219 element custom:streamline-card TypeError: Cannot read properties of undefined (reading 'floor_image_generic')
    at t.parseConfig (streamline-card.js?hacstag=839495072007:298:46)
    at t.setConfig (streamline-card.js?hacstag=839495072007:318:42)
    at r (create-element-base.ts:125:11)
    at create-element-base.ts:146:12
    at h (create-element-base.ts:252:12)
    at c (create-element-base.ts:209:12)
    at d (create-hui-element.ts:25:10)
    at a (create-styled-hui-element.ts:7:19)
    at o.value (hui-picture-elements-card.ts:186:21)
    at hui-picture-elements-card.ts:89:32
c @ create-element-base.ts:219Understand this error
create-element-base.ts:219 card image Error: Unknown type encountered: image
    at h (create-element-base.ts:282:9)
    at c (create-element-base.ts:209:12)
    at Module.v (create-card-element.ts:103:3)
    at t.setConfig (streamline-card.js?hacstag=839495072007:322:26)
    at r (create-element-base.ts:125:11)
    at create-element-base.ts:146:12
    at h (create-element-base.ts:252:12)
    at c (create-element-base.ts:209:12)
    at d (create-hui-element.ts:25:10)
    at a (create-styled-hui-element.ts:7:19)
```
Using decluttering-card it's fine:
![image](https://github.com/user-attachments/assets/1b48d30b-a2d4-427a-a7d7-9f0adf20cd21)

Regards
