### ISSUE TITLE
Handle default value

### ISSUE THREAD

**Issue by Pulpyyyy** [brunosabot/streamline-card#15]
Thanks for closing https://github.com/brunosabot/streamline-card/issues/12

Here is another one ;)
As soon as card define a default variable, rendre is broken

```
  floor_cover_void_img:
    default:
      type: volet
      etg: rdc
    element:
      type: image
      entity: sensor.[[type]]_[[area]]
      style:
        top: 50%
        left: 50%
        width: 100%
      image: /local/images/empty.png
      tap_action:
        action: none
```
According to logs :
```
create-element-base.ts:219 element custom:streamline-card TypeError: (e.default ?? []) is not iterable
    at getVariables (streamline-card.js?hacstag=839495072008:223:81)
    at evaluateVariables (streamline-card.js?hacstag=839495072008:239:13)
    at evaluateConfig (streamline-card.js?hacstag=839495072008:245:11)
    at t.parseConfig (streamline-card.js?hacstag=839495072008:311:22)
    at t.setConfig (streamline-card.js?hacstag=839495072008:320:42)
    at r (create-element-base.ts:125:11)
    at create-element-base.ts:146:12
    at h (create-element-base.ts:252:12)
    at c (create-element-base.ts:209:12)
    at d (create-hui-element.ts:25:10)
```

Regards

**Comment by andreasbrett** [comment]
You need to define the default values as list:

```yaml
  floor_cover_void_img:
    default:
      - type: volet
      - etg: rdc
    element:
      type: image
      entity: sensor.[[type]]_[[area]]
      style:
        top: 50%
        left: 50%
        width: 100%
      image: /local/images/empty.png
      tap_action:
        action: none
```
