### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by andreasbrett** [brunosabot/streamline-card#17]
**Describe the bug**  
I receive the following error when not specifying variables.

```
Cannot convert undefined or null to object
type: custom:streamline-card
template: gap
```

**To Reproduce**  
template:
```yaml
  gap:
    default:
      - height: 12px
    card:
      type: markdown
      content: ' '
      card_mod:
        style: |
          ha-card {
            max-height: [[height]];
            background: none;
          }
```

template usage:
```yaml
type: custom:streamline-card
template: gap
```

**Informations (please complete the following information):**

- OS: Android/Windows
- Browser/App: Chrome
- Streamline Card version: 0.0.9
- Home Assistant version: 2024.9.1
