### ISSUE TITLE
Visibility parameter in template does not work

### ISSUE THREAD

**Issue by CykloneFij** [brunosabot/streamline-card#18]
When using visibility for a card template, it will get removed if editing the template through the visual editor.
So, I add this to a card in code editor:

```
  - type: custom:streamline-card
    template: live_tile
    variables:
      entity: light.kitchen_sink
      color: yellow
      timer_sensor: sensor.timer_percent_motion_kitchen
    visibility:
      - condition: state
        entity: light.kitchen_sink
        state: 'on'

```
and then switch to visual editor and save, the visibility section is removed.
Now, if I add to the template:

```
streamline_templates:
  live_tile:
    card:
      type: tile
      entity: '[[entity]]'
      tap_action:
        action: more-info
      icon_tap_action:
        action: toggle
      color: '[[color]]'
      state_content:
        - state
        - last_changed
      visibility:
        - condition: state
          entity: '[[entity]]'
          state: 'on'

````

.,. it will work, until I go to edit the dashboard again, the browser tab crashes.  I have to delete the dashboard as I can't find a way to edit it after adding the visibility section in the template in the raw config editor.
Am I missing something?
