### ISSUE TITLE
Visibility settings from template are not respected

### ISSUE THREAD

**Issue by hco** [brunosabot/streamline-card#2]
If you configure visibility in the template, the card is always visible.
I think this is a bug or should be documented as not working.

**To Reproduce**  
1. Copy & paste the yaml below as a new dashboard
2. Leave the edit mode
3. The card using streamline-card will be visible 😿 
**Expected behavior**  
I expected both cards to be hidden.

**Screenshots**  
![CleanShot 2024-08-22 at 14 20 45@2x](https://github.com/user-attachments/assets/86659f52-8553-4b78-83bb-360d4ad00239)
**YAML**  
```
streamline_templates:
  visibility_test:
    card:
      type: markdown
      content: I should not be visible, but sadly I am.
      visibility:
        - condition: screen
          media_query: ''
views:
  - title: Test
    type: sections
    sections:
      - type: grid
        cards:
          - type: custom:streamline-card
            template: visibility_test
        title: Hardcoded
      - type: grid
        cards:
          - type: markdown
            content: I am not visible.
            visibility:
              - condition: screen
                media_query: ''
        title: Streamline
```

**Informations (please complete the following information):**

- Bubble Card version: 0.0.4
- Home Assistant version: 2024.8.2

---

Thank you for your work on this card! 🍻
