### ISSUE TITLE
Streamline for type:grid

### ISSUE THREAD

**Issue by aqwserf** [brunosabot/streamline-card#29]
**Describe the bug**  
When I try to streamline a card of type `grid`, I get a weird behavior: the card is definitely not displaying as expected, but maybe I'm trying to do something that this card is not supposed to do/handle.

**To Reproduce**  

Copy/paste the code below

**Expected behavior**  
I would expect the card to render as it is without streamlining it.

**Screenshots**  

![streamline](https://github.com/user-attachments/assets/233ef035-fd1a-4655-8016-447ade7906de)

**YAML**  
These are a couple of tests to find a way.
What I would like to achieve is rendering the 1st card (`original` on the screenshot), with the code of `test`

```yaml
streamline_templates:
  controls_grid_vertical:
    card:
      type: vertical-stack
      cards:
        - type: heading
          heading: Configuration
          heading_style: title
          icon: ''
          layout_options:
            grid_columns: full
            grid_rows: 1
          badges:
            - type: entity
              show_state: true
              show_icon: true
              entity: sensor.outside_average_temperature
              color: green
              tap_action:
                action: more-info
              state_content: state
        - type: entities
          entities:
            - type: custom:auto-entities
              show_empty: false
              filter:
                include:
                  - domain: switch
                    entity_id: /.*plug.*/
                    area: '[[area]]'
              card:
                type: custom:fold-entity-row
                open: true
                state_color: true
                group_config:
                  secondary_info: last-changed
                head:
                  type: custom:template-entity-row
                  icon: mdi:power-plug
                  name: Prises
                  state: ''
              sort:
                method: friendly_name
                numeric: false
                reverse: false
            - type: custom:auto-entities
              show_empty: false
              filter:
                include:
                  - domain: automation
                    area: '[[area]]'
              card:
                type: custom:fold-entity-row
                state_color: true
                group_config:
                  secondary_info: last-updated
                head:
                  type: custom:template-entity-row
                  icon: mdi:home-automation
                  name: Automatisations
                  state: ''
              sort:
                method: friendly_name
                numeric: false
                reverse: false
  controls:
    card:
      type: entities
      entities:
        - type: custom:auto-entities
          show_empty: false
          filter:
            include:
              - domain: switch
                entity_id: /.*plug.*/
                area: '[[area]]'
          card:
            type: custom:fold-entity-row
            open: true
            state_color: true
            group_config:
              secondary_info: last-changed
            head:
              type: custom:template-entity-row
              icon: mdi:power-plug
              name: Prises
              state: ''
          sort:
            method: friendly_name
            numeric: false
            reverse: false
        - type: custom:auto-entities
          show_empty: false
          filter:
            include:
              - domain: automation
                area: '[[area]]'
          card:
            type: custom:fold-entity-row
            state_color: true
            group_config:
              secondary_info: last-updated
            head:
              type: custom:template-entity-row
              icon: mdi:home-automation
              name: Automatisations
              state: ''
          sort:
            method: friendly_name
            numeric: false
            reverse: false
  heading_configuration:
    card:
      type: heading
      heading: 🔧 Configurations
      heading_style: title
      icon: ''
      layout_options:
        grid_columns: full
        grid_rows: 1
  heading_controls:
    card:
      type: heading
      heading: Contrôles
      heading_style: subtitle
      icon: ''
      layout_options:
        grid_columns: full
        grid_rows: 1
      badges:
        - type: entity
          show_state: true
          show_icon: true
          entity: sensor.outside_average_temperature
          color: green
          tap_action:
            action: more-info
          state_content: state
  test:
    card:
      type: grid
      cards:
        - type: custom:streamline-card
          template: heading_controls
        - type: custom:streamline-card
          template: controls
views:
  - icon: mdi:test-tube
    title: Test
    path: test
    visible:
      - user: 832269f0ee464f5fa880015c64c5b643
    cards: []
    badges: []
    type: sections
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Controle
            heading_style: subtitle
            icon: ''
            layout_options:
              grid_columns: full
              grid_rows: 1
            badges:
              - type: entity
                show_state: true
                show_icon: true
                entity: sensor.outside_average_temperature
                color: green
                tap_action:
                  action: more-info
                state_content: state
          - type: entities
            entities:
              - type: custom:auto-entities
                show_empty: false
                filter:
                  include:
                    - domain: switch
                      entity_id: /.*plug.*/
                      area: home
                card:
                  type: custom:fold-entity-row
                  open: true
                  state_color: true
                  group_config:
                    secondary_info: last-changed
                  head:
                    type: custom:template-entity-row
                    icon: mdi:power-plug
                    name: Prises
                    state: ''
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
              - type: custom:auto-entities
                show_empty: false
                filter:
                  include:
                    - domain: automation
                      area: home
                card:
                  type: custom:fold-entity-row
                  state_color: true
                  group_config:
                    secondary_info: last-updated
                  head:
                    type: custom:template-entity-row
                    icon: mdi:home-automation
                    name: Automatisations
                    state: ''
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
      - type: grid
        cards:
          - type: custom:streamline-card
            template: heading_configuration
          - type: custom:streamline-card
            template: controls
            variables:
              - area: home
      - type: grid
        cards:
          - type: custom:streamline-card
            template: controls_grid_vertical
            variables:
              - area: home     
      - type: custom:streamline-card
        template: test
    max_columns: 4
```

**Informations (please complete the following information):**

- OS: Linux
- Browser/App: FF
- Streamline Card version: 0.0.14
- Home Assistant version: 2014.10.4

**Additional context**  
I know it might be an edge case but it would be nice to streamline an entire card of type `grid` to avoid copy/paste code around dashboards.
Maybe it's not possible, I'm not using this card properly or is there another way?

Thank you! 🍻

**Comment by brunosabot** [comment]
Hello @aqwserf 

Sorry for the late answer.
You can indeed not do that: the grid you are trying to replace with the streamline-card is not a card, it's a section.
Unfortunately, grid section and grid card have the very same format

**Comment by aqwserf** [comment]
@brunosabot thanks for the answer!
So no way to do that, too bad :)
And why do you say unfortunately? Because of the confusion I made?
I however noticed another weird behavior:

![image](https://github.com/user-attachments/assets/5138658f-601d-4a87-be9a-7541930794a8)

On the left, I'm using a streamline-card like this (as I can't streamline a section as you said):
```
type: grid
cards:
  - type: custom:streamline-card
    template: heading_configuration
  - type: custom:streamline-card
    template: controls
```
In the middle it's a classic one:
```
type: grid
cards:
  - type: heading
    heading: ASD
    heading_style: title
    icon: mdi:air-humidifier-off
  - type: heading
    icon: mdi:fridge
    heading: Cuisine
    heading_style: subtitle
```
And on the right:
```
type: grid
cards:
  - type: heading
    heading: ASDASD
    heading_style: title
```

I notice that the positioning is not respected with the streamline card (no space above the title). Is that expected?
Thanks!
