### ISSUE TITLE
latency on the dashboard

### ISSUE THREAD

**Issue by pctetra** [brunosabot/streamline-card#32]
Hello,
i have a latency problem on a dashboard with mini-graph-cards (this dashboard groups about ten mini-graph-cards), the temperature and humidity curves appear with a delay of 2 to 3 seconds, this problem does not occur with decluttering-templates.
I asked the question on the HACF forum it seems that I am not the only one.

yaml example with decluttering-card without latency, the same with streamline has 2-3 seconds latency

```
  mini-graph-card_version_0:
    card:
      type: custom:mini-graph-card
      name: '[[name1]]'
      height: 120
      hours_to_show: 24
      points_per_hour: 4
      hour24: true
      line_width: 2
      font_size: 80
      decimals: 1
      entities:
        - entity: '[[entity1]]'
          name: '[[name2]]'
          show_legend: true
          y_axis: secondary
          color: '[[color1]]'
        - entity: '[[entity2]]'
          name: '[[name3]]'
          show_legend: true
          show_state: true
          color: '[[color2]]'
```
```
type: custom:decluttering-card
template: mini-graph-card_version_0
variables:
  - entity1: sensor.cuisine_4c65a8dba7cd_lywsdcgq_tempc
  - entity2: sensor.cuisine_4c65a8dba7cd_lywsdcgq_hum
  - entity3: sensor.cuisine_4c65a8dba7cd_lywsdcgq_batt
  - name1: Cuisine
  - name2: Température
  - name3: Humidité
  - color1: ""
  - color2: ""
```

Regards
