### ISSUE TITLE
Javascript template

### ISSUE THREAD

**Issue by guyrst** [brunosabot/streamline-card#34]
Bonjour Bruno,

voici mon 'streamline_template' pour une carte history

card_history:
  card:
    type: history-graph
    entities:
      entity_javascript: "states[sensor.visibility_entity].state"
    hours_to_show: 48
    logarithmic_scale: false
    show_names: false

sensor.visibility_entity existe et contient la valeur: switch.test_switch

L'évaluation de entity_javascript retourne: sensor is not defined

Sur quelque chose qui me semblait très simple, je bloque..

Merci pour votre travail.
Cordiales salutations de Guy Rosati

**Comment by pganansia** [comment]
I think quotes are missing around the entity states['sensor.visibility_entity'].state
Rgds

**Comment by brunosabot** [comment]
@guyrst Comme l'a dit @pganansia, il manque les guillemets:
```
card:
  type: history-graph
  entities:
    - entity_javascript: "states['sensor.visibility_entity'].state"
      hours_to_show: 48
      logarithmic_scale: false
      show_names: false
```
