### ISSUE TITLE
Assistance with javascript conditional

### ISSUE THREAD

**Issue by muddro1** [brunosabot/streamline-card#38]
Hoping someone with better skills than me can assist. I am trying to make a reusable bubble card that works for my main use cases lights and fans). I am trying to creates a styles portion of a bubble card that is conditional on the entity being a fan so that way i can have the rotating fan icon when an item is on. I am a bit stuck on how to make that work:

```  rooms-light:
    default:
      - type: slider
    card:
      type: custom:bubble-card
      card_type: button
      entity: '[[entity]]'
      scrolling_effect: false
      icon: '[[icon]]'
      button_type: '[[type]]'
      tap_action:
        action: toggle
      double_tap_action:
        action: more-info
      hold_action:
        action: more-info
      styles_javascript: |2-
          .bubble-icon {
            animation: ${hass.states['[[entity]]'].state === 'on' ? 'slow-rotate 2s linear infinite' : ''};
          }
          @keyframes slow-rotate {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
          }
```

I havent modified the styles section aside from adding _javascript and [[entity]] to the condition from whats provided on thebubble cards repo. Any help would be appreciated.

**Comment by brunosabot** [comment]
There are two things:
 - The whole javascript should return a string, but it's not.
 - The `hass` variable is not accessible, you can directly use `states`

This one works:
```yaml
default:
  - type: slider
card:
  type: custom:bubble-card
  card_type: button
  entity: '[[entity]]'
  scrolling_effect: false
  icon: '[[icon]]'
  button_type: '[[type]]'
  tap_action:
    action: toggle
  double_tap_action:
    action: more-info
  hold_action:
    action: more-info
  styles_javascript: |
    `
      .bubble-icon {
        animation: ${states['[[entity]]'].state === 'on' ? 'slow-rotate 2s linear infinite' : ''};
      }
      @keyframes slow-rotate {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
      }
    `
```
