### ISSUE TITLE
Potentially incorrect recursive call to evaluate Javascript

### ISSUE THREAD

**Issue by agrinevsky** [brunosabot/streamline-card#40]
**Describe the bug**  
When Javascript is being evaluated, variables are not being passed recursively for nested objects. So if I want to write js code that needs to access variables from nested objects - it is impossible to do.

Specific lines:
1. https://github.com/brunosabot/streamline-card/blob/main/src/evaluateJavascript-helper.js#L23
2. https://github.com/brunosabot/streamline-card/blob/main/src/evaluateJavascript-helper.js#L49

Happy to submit a PR if this is indeed an issue and not an intended behavioe

**To Reproduce**  
Here is a sample template

```yaml
streamline_templates:
  area_popup:
    default:
      sensor:
        entity: sensor.kitchen_temperature
        name: Temperature
        show_icon: true
        state_background: false
        show_state: true
        show_background: false
    card:
      type: vertical-stack
      cards:
        - type: custom:bubble-card
          card_type: separator
          show_icon: true
          name: '[[title]]'
          icon: '[[icon]]'
          sub_button_javascript: |
            console.log(variables)
            variables['sensor']
```
