### ISSUE TITLE
Grid options (layout) disappears after edit

### ISSUE THREAD

**Issue by PieterBoeren** [brunosabot/streamline-card#42]
**Describe the bug**  
When setting layout options on a Streamline Card (like the number of colums, or make it full width), it works, but when you edit the card again, the options are removed.

**To Reproduce**  

1. Add a Streamline Card (in the UI)
2. Click on 'Layout'
3. Click the 'Full width card' option
4. Save
5. Edit the same card
6. Click on 'Layout'
7. Options are reset to their defaults

**Expected behavior**  
Layout settings to be retained between edits

**YAML**  

After initial save:
```yaml
type: custom:streamline-card
template: test
variables:
  name: Test
  icon: mdi:account
grid_options:
  columns: full
```
Right after you edit the card (`grid_options` are gone):

```yaml
type: custom:streamline-card
template: test
variables:
  name: Test
  icon: mdi:account
```

**Informations (please complete the following information):**

- OS: Windows
- Browser/App: Chrome
- Streamline Card version: 0.0.21
- Home Assistant version: 2025.1.4
