### ISSUE TITLE
Report the properties in the template

### ISSUE THREAD

**Issue by Arubinu** [brunosabot/streamline-card#49]
Hello, while making a vertical template I came up against the fact that it is not possible to add properties to the template without going through the variables.

By this I mean that if I want to add cards manually in the template call, this is not taken into account.

```yaml
streamline_templates:
  vertical_in_card:
    card:
      type: vertical-stack
      in_card: true
      card_mod:
        style: |
          ha-card {
            backdrop-filter: var(--ha-card-backdrop-filter, none);
          }
  tile_in_card:
    card:
      type: tile
      features_position: inline
      vertical: false
      card_mod:
        style: |
          ha-card {
            backdrop-filter: none;
          }
views:
  - title: Test
    sections:
      - type: grid
        cards:
          - type: custom:streamline-card
            template: vertical_in_card
            cards:
              - type: custom:streamline-card
                template: tile_in_card
                entity: light.test_light
```

Would it be possible to take all these properties into account?

**Comment by brunosabot** [comment]
Right now the only way of passing data is through variables. What you are trying to do can be done this way:
```yaml
streamline_templates:
  vertical_in_card:
    card:
      type: vertical-stack
      in_card: true
      cards: '[[cards]]'
      card_mod:
        style: |
          ha-card {
            backdrop-filter: var(--ha-card-backdrop-filter, none);
          }
  tile_in_card:
    card:
      type: tile
      entity: '[[entity]]'
      features_position: inline
      vertical: false
      card_mod:
        style: |
          ha-card {
            backdrop-filter: none;
          }
views:
  - title: Test
    sections:
      - type: grid
        cards:
          - type: custom:streamline-card
            template: vertical_in_card
            variables:
              cards:
                - type: custom:streamline-card
                  template: tile_in_card
                  variables:
                    entity: light.test_light
```

I don't plan (at least for now) to remove the `variables` overhead
