### ISSUE TITLE
Unable to use templates for an entity list

### ISSUE THREAD

**Issue by Arubinu** [brunosabot/streamline-card#51]
**Describe the bug:**  
Templates do not work on entity lists since a streamline template requires a "type", except the given elements are not maps.

**Expected behavior:**  
As with maps, allow you to duplicate the elements of the list (using the same template).

**Screenshots:**  
![Image](https://github.com/user-attachments/assets/319e803a-2fc1-4e37-92bc-1ea1608630b6)

**YAML:**  
```yaml
streamline_templates:
  entitie_in_entities:
    card:
      entity: '[[entity]]'
      name: '[[name]]'
      secondary_info: last-changed
      state_color: true
      card_mod:
        style:
          .: |
            hui-generic-entity-row {
              margin: -8px 0;
            }
          hui-generic-entity-row$: |
            .secondary {
              margin-top: -2px !important;
              font-weight: 400;
              font-size: 12px;
              line-height: 16px;
              letter-spacing: 0.4px;
            }
            .secondary, ha-relative-time {
              color: var(--primary-text-color) !important;
            }
views:
  - title: Test
    sections:
      - type: grid
        column_span: 4
        cards:
          - type: entities
            entities:
              - type: custom:streamline-card
                template: entitie_in_entities
                variables:
                  entity: binary_sensor.couloir_entree_contact_porte_contact
                  name: Porte d'Entrée
              - entity: binary_sensor.couloir_chambres_contact_porte_contact
                name: Porte du Couloir
                secondary_info: last-changed
                state_color: true
              - entity: binary_sensor.cuisine_contact_porte_contact
                name: Porte de la Cuisine
                secondary_info: last-changed
                state_color: true
              - entity: binary_sensor.salon_contact_porte_contact
                name: Porte du Salon
                secondary_info: last-changed
                state_color: true
              - entity: binary_sensor.salle_d_eau_contact_porte_contact
                name: Porte de la Salle d'eau
                secondary_info: last-changed
                state_color: true
              - entity: binary_sensor.salle_de_bain_contact_porte_contact
                name: Porte de la Salle de bain
                secondary_info: last-changed
                state_color: true
              - entity: binary_sensor.toilette_contact_porte_contact
                name: Porte des Toilettes
                secondary_info: last-changed
                state_color: true
```

**Informations:**
- Streamline Card version: 0.0.22
- Home Assistant version: 2025.3.4

**Additional context:**  
I removed the `card_mod` part of all entities to avoid having too large a YAML code, but that's why I would like to use Streamline Card, among other things.

**Comment by ivanfmartinez** [comment]
@brunosabot  I dont understand if my case is same but I have tried this simple template and does not work, no error message just empty card show.

No variables, I just want to reuse a simple card. I'm using in the streamline_templates.yaml file this code, in the same file I have other templates (with other types) that are working:

```
controles_XXXX:
  card:
    type: entities
    entities:
      - entity: lock.volvo_XXXX_lock
        secondary_info: last-changed
      - entity: lock.volvo_XXXX_lock_reduced_guard
        secondary_info: last-changed
      - entity: button.volvo_XXXX_climatization_start
        secondary_info: last-changed
      - entity: script.volvo_XXXX_modo_pet
        secondary_info: last-changed
      - entity: button.volvo_XXXX_climatization_stop

```

**Comment by brunosabot** [comment]
Hey @ivanfmartinez this is a bug that will be fixed in the next version. See #58

**Comment by Arubinu** [comment]
Hello @brunosabot, I just tried your method by adding a return in front of the "map". But I got the following result:

![Image](https://github.com/user-attachments/assets/29b76dbf-f0a8-43eb-b2aa-3e41f019e017)
![Image](https://github.com/user-attachments/assets/ff8c6088-7080-4591-a01b-cd77773a3f75)

Here is the complete code:
```yaml
streamline_templates:
    vertical_entities:
    card:
      type: entities
      entities_javascript: |
        return variables.list.map(({entity, name}) => ({
          entity: entity,
          name: name,
          secondary_info: 'last-changed',
          state_color: true,
          card_mod: {
            style: {
              '.': `
                hui-generic-entity-row {
                  margin: -8px 0;
                }
                hui-generic-entity-row$: |
                  .secondary {
                    margin-top: -2px !important;
                    font-weight: 400;
                    font-size: 12px;
                    line-height: 16px;
                    letter-spacing: 0.4px;
                  }
                  .secondary, ha-relative-time {
                    color: var(--primary-text-color) !important;
                  }`
            }
          }
        }));
views:
  - title: Test
    sections:
      - type: grid
        cards:
          - type: custom:streamline-card
            template: vertical_entities
            variables:
              list:
                - entity: binary_sensor.couloir_entree_contact_porte_contact
                  name: Porte d'Entrée
                  secondary_info: last-changed
                  state_color: true
                - entity: binary_sensor.couloir_chambres_contact_porte_contact
                  name: Porte du Couloir
                  secondary_info: last-changed
                  state_color: true
                - entity: binary_sensor.cuisine_contact_porte_contact
                  name: Porte de la Cuisine
                  secondary_info: last-changed
                  state_color: true
                - entity: binary_sensor.salon_contact_porte_contact
                  name: Porte du Salon
                  secondary_info: last-changed
                  state_color: true
                - entity: binary_sensor.salle_d_eau_contact_porte_contact
                  name: Porte de la Salle d'eau
                  secondary_info: last-changed
                  state_color: true
                - entity: binary_sensor.salle_de_bain_contact_porte_contact
                  name: Porte de la Salle de bain
                  secondary_info: last-changed
                  state_color: true
                - entity: binary_sensor.toilette_contact_porte_contact
                  name: Porte des Toilettes
                  secondary_info: last-changed
                  state_color: true
```
