### ISSUE TITLE
Tile card feature type template does not work

### ISSUE THREAD

**Issue by bladecell** [brunosabot/streamline-card#52]
**Describe the bug**  
Templating feature type in tile card does not seem to woek

**Screenshots**  

![Image](https://github.com/user-attachments/assets/6c95aa27-26e8-4085-80cf-d7701298cdf0)

**YAML**  

```yaml
variables:
  entity: light.esph_kitchen_countertop_switch
card:
  features:
    - type_javascript: "states['[[entity]]'].attributes.brightness === null ? 'toggle' : 'light-brightness'"
  type: tile
  name_javascript: "states['[[entity]]'].attributes.brightness === null ? 'toggle' : 'light-brightness'"
  entity: "[[entity]]"
  features_position: bottom
  vertical: false
  state_content:
    - state
    - last_changed
```

**Additional context**  
I wanted to template the feature type in tile card to have feature type switch if the entity does not have brightness attribute or light-brightness feature if it has. But I am getting an error. For debug I have templated the same way the tile name which returns the feature type I need.

Thank you! 🍻
