### ISSUE TITLE
bubble-card popup don't work

### ISSUE THREAD

**Issue by rldalex** [brunosabot/streamline-card#56]
I recently discovered streamiine-card and I recode my entire interface to use templates. I can make them all work except with bubble card popups.

Example in UI:

```
- type: custom:streamline-card
   template: popup_template
   variables:
      - hash: "#test"
```
         
In file: popup_template.yaml

```
default:
  - hash: home
card:
  type: custom:bubble-card
  card_type: pop-up
  hash: "[[hash]]"
  modules:
    - default
```

When I click the button that sends me to the path #test, nothing happens.

Do you have any idea what's wrong?
Thanks in advance.
Alex

**Comment by brunosabot** [comment]
Hello @rldalex

Per bubble Card implementation, the popup must be the child of a vertical-stack card.
Be careful though: the popup should be the DIRECT descendent 
```yaml
# WRONG - In UI
type: vertical-stack
cards:
  - type: custom:streamline-card
    template: popup_template
    # There is a streamline card component between vertical stack and popup
```

```yaml
# RIGHT - In template
default:
  - hash: home
card:
  type: vertical-stack
  cards:
      type: custom:bubble-card
      card_type: pop-up
      hash: "[[hash]]"
      modules:
        - default
```
This behavior is 100% related to how Bubble Card works. It won't be fixed by streamline card
