### ISSUE TITLE
Entities in an streamline card no longer work

### ISSUE THREAD

**Issue by aqwserf** [brunosabot/streamline-card#58]
**Describe the bug**  
After upgrading to 0.0.23, my templates declared [using the UI](https://ha.hysteresis.lan/hacsfiles/streamline-card/streamline_templates.yaml) no longer work.
If I revert back to 0.0.22, everything works.
I tried copying the file `/root/config/www/community/streamline-card/streamline_templates.example.yaml` as `/root/config/www/community/streamline-card/streamline_templates.yaml`, thinking that the module needed this file even if not used, but it doesn't work. 
After some digging, I noticed that declaring a `type: entities` might be the culprit. If I "transform" it to an simple `type: entity`, it works again.

**To Reproduce**  

1. Create the yaml below
2. Save
3. `test_entities` does not appear while the exact same entities declared outside the streamline template  works

**Expected behavior**  
Entities can be in a template again

**Screenshots**  
![Image](https://github.com/user-attachments/assets/11766867-a6be-431d-928e-2c6b84073de6)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
streamline_templates:
  test_entity:
    card:
      type: entity
      entity: sensor.33_weather_alert
  test_entities:
    card:
      type: entities
      entities:
        - entity: light.office_lights
  example_tiles:
    card:
      type: tile
      entity: '[[entity]]'
      features_position: bottom
      vertical: false          
views:
  - type: sections
    max_columns: 4
    title: test 1
    path: test-1
    sections:
      - type: grid
        cards:
          - type: custom:streamline-card
            template: example_tiles
            variables:
              entity: sensor.33_weather_alert
          - type: custom:streamline-card
            template: test_entity
          - type: custom:streamline-card
            template: test_entities
          - type: entities
            entities:
              - entity: light.office_lights     
```

**Informations (please complete the following information):**

- OS: HAOS 15.2
- Browser/App: Firefox
- Streamline Card version: 0.0.23
- Home Assistant version: 2025.4.3

**Additional context**  

Thank you! 🍻
