### ISSUE TITLE
Occasional issue when using with Bubble Card buttons

### ISSUE THREAD

**Issue by andreasbrett** [brunosabot/streamline-card#6]
**Describe the bug**  
See https://github.com/Clooos/Bubble-Card/issues/763. I migrated from Decluttering Card to Streamline Card and have issues for my templates that create a Bubble Card Button for a scene entity. Occasionally the scene entities are returned as undefined to Bubble Card. I switched back some of my buttons from Streamline to Decluttering and while the Decluttering ones work, the Streamline ones don't work.

**YAML**  
If applicable, add any relevant YAML code.

```yaml
streamline_templates:
  scene_button:
    default:
      color_icon: '#FF9E00'
      color_bg1: ''
      color_bg2: ''
    card:
      type: custom:bubble-card
      card_type: button
      button_type: switch
      entity: '[[entity]]'
      name: '[[name]]'
      icon: mdi:[[icon]]
      tap_action:
        action: call-service
        service: scene.turn_on
        target:
          entity_id: '[[entity]]'
      double_tap_action:
        action: none
      hold_action:
        action: none
      button_action:
        tap_action:
          action: call-service
          service: scene.turn_on
          target:
            entity_id: '[[entity]]'
        double_tap_action:
          action: none
        hold_action:
          action: none
      styles: |
        ha-card > div > div > div > div > ha-icon {
          ${hass.states['[[helper]]'].state === '[[entity]]' ? 'color: [[color_icon]] !important; opacity: 100% !important;' : '' }
        }
        ha-card > div > div > div {
          background: linear-gradient([[color_bg1]], [[color_bg2]]) !important;
        }
```

```yaml
- type: custom:streamline-card
  template: scene_button
  variables:
    - entity: scene.wohnzimmer_orange_teal
    - name: Orange & Teal
    - helper: input_text.aktuelle_szene_wohnzimmer
    - icon: fire
    - color_bg1: darkorange
    - color_bg2: deepskyblue
```

**Informations (please complete the following information):**

- OS: OS-independent
- Browser/App: HA Mobile App, Chrome
- Streamline Card version: 0.0.5
- Home Assistant version: 2024.8.3 (but also on 2024.9.0b2)

**Comment by brunosabot** [comment]
Hello @andreasbrett,

First, thanks for the bug report.
Can you share your scene with me? I tried to implement it, but I wasn't able to reproduce the bug.
Also, can you tell me: if that happens on page load? On tab change? On scene change? Randomly after some time?

**Comment by andreasbrett** [comment]
It happens randomly (I know the worst case for debugging). I don't think it is about the scenes themselves but maybe about the way I configured scenes in HA (stored in yaml) or my dynamic use of scenes (when there's inactivity in a room I store the current light setup in a scene, that is later recalled when there's motion again).

My configuration yaml contains this include.
```yaml
scene: !include ../scenes.yaml
```

Here's one scene in YAML.
```yaml
- id: 1636221bqz9w8
  name: 'Wohnzimmer: Teal & Pink'
  entities:
    light.stehlampe_gros_wohnzimmer:
      min_color_temp_kelvin: 1901
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 526
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      - hs
      friendly_name: Stehlampe groß (Wohnzimmer)
      supported_features: 44
      color_mode: hs
      brightness: 255
      hs_color:
      - 204
      - 100
      rgb_color:
      - 0
      - 153
      - 255
      xy_color:
      - 0.143
      - 0.176
      state: 'on'
    light.stehlampe_klein_wohnzimmer:
      min_color_temp_kelvin: 1901
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 526
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      - hs
      friendly_name: Stehlampe klein (Wohnzimmer)
      supported_features: 44
      color_mode: hs
      brightness: 255
      hs_color:
      - 330
      - 95
      rgb_color:
      - 255
      - 12
      - 133
      xy_color:
      - 0.571
      - 0.241
      state: 'on'
    light.deckenlampen_wohnzimmer:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 370
      effect_list:
      - blink
      - breathe
      - okay
     - channel_change
      - finish_effect
      - stop_effect
      supported_color_modes:
      - color_temp
      friendly_name: Deckenlampen (Wohnzimmer)
      supported_features: 44
      state: 'off'
    light.led_streifen_tv_wohnzimmer_rgb:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6666
      min_mireds: 150
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      friendly_name: LED Streifen TV (Wohnzimmer)_rgb
      supported_features: 40
      color_mode: xy
      brightness: 255
      hs_color:
      - 204.194
      - 97.255
      rgb_color:
      - 7
      - 155
      - 255
      xy_color:
      - 0.143
      - 0.176
      state: 'on'
    light.led_streifen_hinten_wohnzimmer:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - blink
      - breathe
      - okay
      - channel_change
      - candle
      - fireplace
      - colorloop
      - finish_effect
      - stop_effect
      - stop_hue_effect
      supported_color_modes:
      - color_temp
      - xy
      friendly_name: LED Streifen hinten (Wohnzimmer)
      supported_features: 44
      color_mode: xy
      brightness: 255
      hs_color:
      - 329.63
      - 95.294
      rgb_color:
      - 255
      - 12
      - 135
      xy_color:
      - 0.571
      - 0.241
      state: 'on'
  icon: mdi:fireplace
  metadata: {}
``` 

I have buttons for all scenes that are static (not the dynamically created ones mentioned above). They all show the error at the same time - so it's not about a particular scene. I think HA reloads the scenes e.g. when dynamic scenes are created through my automations which causes hickups in streamline card. Sometimes when I go over to the scene editor in the HA UI, open a scene there and go back to my Lovelace dashboard, the scene buttons work again. They almost always work again when I activate a scene (either through voice command or through the HA settings).

Some info on how I create the dynamic scenes. I use the `scene.create` action and provide snapshot entities. These are runtime scenes not stored in the `scenes.yaml` file - they're not stored in registry and won't survive a HA reboot.

```yaml
action: scene.create
data:
  snapshot_entities:
    - light.xxx
    - light.yyy
    - ...
  scene_id: wohnzimmer_standby
```
