### ISSUE TITLE
Issue using multiple variables on a single line

### ISSUE THREAD

**Issue by cfoxga** [brunosabot/streamline-card#65]
I have a complex card that ran into an issue when using multiple variables on a single line. 

Here is the line from the decluttering card:

  entity: 'number.[[prefix]]_g[[index]]_move_threshold'

If I pass prefix=basement_office_multisensor and index=8, decluttering card correctly returns:

  'number.basement_office_multisensor_g8_move_threshold'

However, streamline-card returned:

  'number.basement_office_multisensor_g[[index]]_move_threshold'

To work around this, I had to use javascript:

  entity_javascript: "return 'number.[[prefix]]_g' + '[[index]]' + '_move_threshold'"

- OS: Windows
- Browser/App: Chrome
- Streamline Card version: v0.1.0
- Home Assistant version: 2025.4.3

Thanks,
Chris

**Comment by brunosabot** [comment]
Hello there,

Even if it's definitely a bug, maybe you can do instead:

`entity: "number.[[prefix]]_g[[index]]_move_threshold"`

**Comment by brunosabot** [comment]
Thanks @ivanfmartinez, with your example I was able to reproduce the issue.
It will be fixed in the next release

**Comment by brunosabot** [comment]
Hello there!
The release has been published. Can you confirm you no longer have the error?

**Comment by ivanfmartinez** [comment]
Sorry for the delay responding that, I have tested today and got error :

```
Configuration error
Expected ',' or '}' after property value in JSON at position 44 (line 1 column 45)
```

tested with this template
```
teste_001:
  default:
    - hours: 36
  card:
    type: entities
    title: "TESTE ([[hours]]h) [[hours]]"
    show_header_toggle: false
    entities:
      - entity: switch.reles_005_z3_4ch_l4
        secondary_info: last-changed
        type: simple-entity

```


Works fine :
- If I remove the second **[[hours]]** 
- If I put anything after second [[hours]] like **"TESTE ([[hours]]h) [[hours]]xxx"**

Apparently it works only if the line does not end with the second variable
