### ISSUE TITLE
Installation assumes HACS

### ISSUE THREAD

**Issue by joeidea** [brunosabot/streamline-card#72]
**Describe the bug**  
A console error is present, MS Edge Version 137.0.3296.68 (Official build) (64-bit). This is in screenshot below.

**To Reproduce**  

1. Manual installation (not HACS)
2. Used Method 2: UI Configuration (same as my decluttering_card use)

**Expected behavior**  
Expect to see no console errors. I am chasing this because the card looks different than expected with decluttering_card; I don't know if this is related. In second screenshot, I expect to see shadow as in "Attic/ Outdoors", which is lacking in "A/V Sockets."

**Screenshots**  

![Image](https://github.com/user-attachments/assets/df313a1e-90e8-456c-8390-5358beca13a8)

![Image](https://github.com/user-attachments/assets/4fc877cc-4462-43d3-9fa1-d951f9922b7e)

**YAML**  

```yaml
type: custom:streamline-card
template: entities_5_rows
variables:
  title: A/V Sockets (Den)
  ent_1: switch.smart_switch_2206179081904651200248e1e9986a8d_outlet
  ent_1_name: Bose Bass 700
  ent_1_icon: mdi:speaker
  ent_2: switch.smart_switch_2312060381133154060148e1e9e501e5_outlet_1
  ent_2_name: Bose Soundbar 900
  ent_2_icon: mdi:soundbar
  ent_3: switch.smart_switch_2312060381133154060148e1e9e501e5_outlet_2
  ent_3_name: Harmony Hub
  ent_3_icon: mdi:remote
  ent_4: switch.smart_switch_2312060381133154060148e1e9e501e5_outlet_3
  ent_4_name: Roku 4850X
  ent_4_icon: mdi:audio-video
  ent_5: switch.smart_switch_2312060381133154060148e1e9e501e5_outlet_4
  ent_5_name: TCL TV
  ent_5_icon: mdi:television
```

**Informations (please complete the following information):**

- OS: Windows 11 Pro (using Hyper-V)
- Browser/App: MS Edge Version 137.0.3296.68 (Official build) (64-bit)
- Streamline Card version: v0.1.0
- Home Assistant version: 2025.5.3

**Additional context**  

Thank you! 🍻
