### ISSUE TITLE
Streamline Card causes frontend crashes on Chrome with some cards (HA 2025.6.0)

### ISSUE THREAD

**Issue by droans** [brunosabot/streamline-card#73]
For any feature request you can open a new discussion here:  
https://github.com/brunosabot/streamline-card/discussions/categories/ideas

For any question you can open a new discussion here:  
https://github.com/brunosabot/streamline-card/discussions/categories/q-a

**Describe the bug**  
With certain cards (such as `conditional` and `vertical-stack`), Chrome will completely freeze and crash. Unfortunately, no logs can be retrieved before the crash occurs. This occurs on Chrome for Windows, Chrome for Android, and the HA Android app. I am not sure if this occurs on any other browser. 

**To Reproduce**  

1. Create templates like the following:
```yaml
streamline_templates:
  test_conditional_card:
    card:
      type: conditional
      conditions:
        - condition: state
          entity_id: sun.sun
          state: above_horizon
      card:
        type: markdown
        content: The sun is above horizon!
  test_stack_card:
    card:
      type: vertical-stack
      cards:
        - type: entities
          entities:
            - sun.sun
        - type: markdown
          content: The sun is {{ state_translated('sun.sun') }}
  ...
```
2. Use templates in frontend config:
```yaml
type: custom:streamline-card
template: test_conditional_card
# or...
type: custom:streamline-card
template: test_stack_card
```
3. Chrome will completely crash when card is loaded outside of editor. 

**Expected behavior**  
There shouldn't be any crashing that occurs. 

**Screenshots**  
N/A

**YAML**  
See above examples

**Informations (please complete the following information):**

- OS: Windows, Android
- Browser/App: Chrome for Windows, Chrome for Android, HA Android App
- Streamline Card version: v0.1.0
- Home Assistant version: 2025.6.0 (Frontend 20250531.2)

**Additional context**  
It seems that with this release, the HA devs seemed to have made some frontend changes to these cards which is causing more issues than expected. EG - the `scheduler-card` is causing scrolling to lock up and panels to automatically close repeatedly when used inside of a `bubble-card` popup with vertical stack.
